### PR TITLE
Update neighborhood model and fixtures

### PR DESCRIPTION
**Pull request by vchrombie**
This commit updates the neighborhood model, adds a few more fields.

It also adds scripts which creates fixtures and load the data in the database.

### CODE REVIEW

**Comment by AlfaroukSaleh** [comment]
The changes seem fine.
There is a conflict in the db.sqlite file, that we can solve together.

**Comment by vchrombie** [comment]
@AlfaroukSaleh, I fixed the issue. It should be good now.

**Comment by AlfaroukSaleh** [comment]
@vchrombie 
Everything seems good to me.
Will merge it.

**Comment by vchrombie** [comment]
Thanks @AlfaroukSaleh!

**Pull request merged**
